services:
  # 統合サービス（フロントエンド + バックエンド）
  - type: web
    name: sales-kpi-app
    runtime: node
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DISCORD_WEBHOOK_URL
        sync: false